### ISSUE TITLE
Issue with new feature (Add AI Group)

### ISSUE THREAD

**Issue by clothillde** [GasiorowskiPiotr/ai-explorer#25]
New Tab: Add AI Group -> Loading data is failing on iOS (safari browser).

**Comment by GasiorowskiPiotr** [comment]
Switching LocalStorage direct implementation to LocalForage wrapper (http://localforage.github.io/localForage/) for improved handling of different browser storage mechanisms

**Comment by GasiorowskiPiotr** [comment]
@clothillde : Which version of iOS are you using? (incl. version of Safari)

**Comment by GasiorowskiPiotr** [comment]
Please check on TEST env (https://ai-explorer-dev.azurewebsites.net/) whether the fix solves your issue

**Comment by clothillde** [comment]
iOS 9.3
Safari Mobile 9

**Comment by clothillde** [comment]
On TEST env it correctly loads the data, but after reshreshing everything is gone.

**Comment by GasiorowskiPiotr** [comment]
The next approach will be to store the key of the AI Group and then, when no AI Apps can be loaded - load them by AI Group Key. If AI Group key cannot be stored - we have no way to overcome this issue.

**Comment by GasiorowskiPiotr** [comment]
Please check again on TEST env (https://ai-explorer-dev.azurewebsites.net/) whether the fix solves your issue

**Comment by GasiorowskiPiotr** [comment]
Please check again on TEST env (https://ai-explorer-dev.azurewebsites.net/) whether the fix solves your issue

**Comment by clothillde** [comment]
Right now it doesn't load the data, the loader is spinning and nothing more is happening.

**Comment by clothillde** [comment]
Turned out that the issue was caused by having private browsing mode on.
After I turned private browsing mode off, everything works fine! :)

**Comment by GasiorowskiPiotr** [comment]
Returning to localForage for all data being stored. Need refactoring saving/loading AI apps.

**Comment by GasiorowskiPiotr** [comment]
Issue ready to be tested (non-private mode --> everything is fine, private mode --> error notification + hide spinner).

**Comment by clothillde** [comment]
Tested. Non-private mode --> everything is fine, private mode --> error notification is visible, spinner is hidden.
